import { Prisma } from '@prisma/client';

/**
 * 파트너/운영자가 **자기** 이벤트를 볼 때의 컬럼.
 *
 * 금액·정원·집계가 전부 보인다 — D-07 이 감추는 상대는 유저이지 이벤트 주인이 아니다.
 * 그래도 select 를 명시하는 이유는 두 가지다: 새 컬럼이 생겨도 응답 모양이 저절로 넓어지지 않고,
 * 이 상수를 import 하는 곳이 곧 "권한 있는 조회 경로"의 전체 목록이 된다(IC-05 의 별도 리포지토리 취지).
 */
export const PARTNER_EVENT_SELECT = {
  id: true,
  venueId: true,
  partnerId: true,
  categoryId: true,
  regionId: true,
  sigunguCode: true,
  title: true,
  slug: true,
  description: true,
  tags: true,
  mode: true,
  status: true,
  statusBeforeSuspend: true,
  capacity: true,
  claimedCount: true,
  soldOutAt: true,
  fixedAmount: true,
  minAmount: true,
  maxAmount: true,
  amountStep: true,
  currency: true,
  applyStartAt: true,
  applyEndAt: true,
  originalApplyEndAt: true,
  rankingLockAt: true,
  serviceStartAt: true,
  serviceEndAt: true,
  serviceDateKst: true,
  depositRequired: true,
  depositType: true,
  depositFixedAmount: true,
  depositPercentBp: true,
  depositRoundingUnit: true,
  depositMinAmount: true,
  depositMaxAmount: true,
  depositWindowMinutes: true,
  depositRefundNote: true,
  softCloseEnabled: true,
  softCloseWindowMinutes: true,
  softCloseExtendMinutes: true,
  softCloseMaxExtensions: true,
  softCloseMaxExtensionsPerUser: true,
  softCloseHardEndAt: true,
  softCloseExtensionCount: true,
  showCompetitionRatio: true,
  ratioMinApplicantsToShow: true,
  cutoffVisibility: true,
  rankVisibility: true,
  amountDistributionVisibility: true,
  liveApplicantCount: true,
  totalApplicationCount: true,
  expiredCount: true,
  canceledCount: true,
  competitionRatioX10: true,
  statsRefreshedAt: true,
  closeReason: true,
  cancelReason: true,
  cancelMemo: true,
  openedAt: true,
  closedAt: true,
  finalizedAt: true,
  canceledAt: true,
  suspendedAt: true,
  suspendedReason: true,
  policyVersion: true,
  version: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.EventSelect;

export type EventSnapshot = Prisma.EventGetPayload<{ select: typeof PARTNER_EVENT_SELECT }>;

/** 편집 화면이 한 번에 필요로 하는 이미지 컬럼. */
export const EVENT_IMAGE_SELECT = {
  id: true,
  blobUrl: true,
  pathname: true,
  width: true,
  height: true,
  byteSize: true,
  mimeType: true,
  blurDataUrl: true,
  altText: true,
  sortOrder: true,
  isCover: true,
  createdAt: true,
} satisfies Prisma.EventImageSelect;
